export const SUBMIT_MESSAGE_START = "SUBMIT_MESSAGE_START";
export const SUBMIT_MESSAGE_SUCCESS = "SUBMIT_MESSAGE_SUCCESS";
export const SUBMIT_MESSAGE_FAIL = "SUBMIT_MESSAGE_FAIL";
export const SUBMIT_MESSAGE_RESET = "SUBMIT_MESSAGE_RESET";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";
export const RESET_MESSAGES = "RESET_MESSAGES";

export const FETCH_MESSAGE_START = "FETCH_MESSAGE_START";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAIL = "FETCH_MESSAGE_FAIL";
export const RESET_MESSAGE = "RESET_MESSAGE";

export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const FILTER_MESSAGES_START = "FILTER_MESSAGES_START";
export const FILTER_MESSAGES_ADD = "FILTER_MESSAGES_ADD";
export const FILTER_MESSAGES_REMOVE = "FILTER_MESSAGES_REMOVE";
export const FILTER_MESSAGES_FAIL = "FILTER_MESSAGES_FAIL";
export const FILTER_MESSAGES = "FILTER_MESSAGES";

export const SORT_MESSAGES_START = "SORT_MESSAGES_START";
export const SORT_MESSAGES_ADD = "SORT_MESSAGES_ADD";
export const SORT_MESSAGES_REMOVE = "SORT_MESSAGES_REMOVE";
export const SORT_MESSAGES_FAIL = "SORT_MESSAGES_FAIL";
export const SORT_MESSAGES = "SORT_MESSAGES";

export const SORT_RESET = "SORT_RESET";
export const FILTER_RESET = "FILTER_RESET";

export const GET_PERSONS_START = "GET_PERSONS_START";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";
export const GET_PERSONS_RESET = "GET_PERSONS_RESET";

export const GET_RESOURCES_START = "GET_RESOURCES_START";
export const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
export const GET_RESOURCES_FAIL = "GET_RESOURCES_FAIL";
export const GET_RESOURCES_RESET = "GET_RESOURCES_RESET";
